
package com.mgreau.mvnbook.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.mgreau.mvnbook.webservice.api.PluginWebService;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ProxyWSPlugin", targetNamespace = "http://webservice.mvnbook.mgreau.com/", wsdlLocation = "http://localhost:8080/mvnbook-webservice/ws-plugin?wsdl")
public class ProxyWSPlugin
    extends Service
{

    private final static URL PLUGININFOIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.mgreau.mvnbook.webservice.client.ProxyWSPlugin.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.mgreau.mvnbook.webservice.client.ProxyWSPlugin.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/mvnbook-webservice/ws-plugin?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/mvnbook-webservice/ws-plugin?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PLUGININFOIMPLSERVICE_WSDL_LOCATION = url;
    }

    public ProxyWSPlugin(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProxyWSPlugin() {
        super(PLUGININFOIMPLSERVICE_WSDL_LOCATION, new QName("http://webservice.mvnbook.mgreau.com/", "PluginWebServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns PluginInfo
     */
    @WebEndpoint(name = "PluginWebServiceImplPort")
    public PluginWebService getPluginWebServiceImplPort() {
        return super.getPort(new QName("http://webservice.mvnbook.mgreau.com/", "PluginWebServiceImplPort"), PluginWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PluginInfo
     */
    @WebEndpoint(name = "PluginWebServiceImplPort")
    public PluginWebService getPluginWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.mvnbook.mgreau.com/", "PluginWebServiceImplPort"), PluginWebService.class, features);
    }

}
